use_frameworks!

target 'EnvChanger_Example' do
  pod 'EnvChanger', :path => '../'

  target 'EnvChanger_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
