os: osx
osx_image: xcode10.2
language: swift

branches:
  only:
    - master

stages:
  - name: lint
    if: branch = master
  - name: compile
    if: branch = master
  - name: deploy
    if: branch = master

jobs:
  include:
      stage: lint
      name: iOS / Xcode 10.2
      cache: cocoapods
      install: gem install cocoapods -v '~> 1.7.5'
      script: pod lib lint

      stage: test
      name: iOS / Xcode 10.2
      script:
        - pod install --project-directory=Example
        - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/EnvChanger.xcworkspace -scheme EnvChanger-Example -sdk iphonesimulator9.2 -destination 'platform=iOS Simulator,OS=12.2,name=iPhone SE' ONLY_ACTIVE_ARCH=NO | xcpretty
      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF ios
      
      stage: deploy
      name: '`pod trunk push`'
      install: gem install cocoapods -v '~> 1.7.0'
      before_script: |
        mv .github/PromiseKit.podspec .
        sed -i '' "s/s.version = '0.0.1'/s.version = '$TRAVIS_TAG'/g" PromiseKit.podspec
      script: |
        set -exo pipefail
        pod trunk push