os: osx
osx_image: xcode10.2
language: swift

branches:
  only:
    - master

stages:
  - name: lint
    if: branch = master
  - name: test
    if: branch = master
  - name: deploy
    if: branch = master

jobs:
  include:
      stage: lint
      install: gem install cocoapods -v '~> 1.7.5'
      script: pod lib lint

      stage: test
      script:
        - pod install --project-directory=Example
        - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/EnvChanger.xcworkspace -scheme EnvChanger-Example -sdk iphonesimulator9.2 -destination 'platform=iOS Simulator,OS=12.2,name=iPhone SE' ONLY_ACTIVE_ARCH=NO | xcpretty
      
      stage: deploy
      install: gem install cocoapods -v '~> 1.7.0'
      script: |
        set -exo pipefail
        pod trunk push